name: Log4JNA Default Build

on:
  push:
    branches:
      - '*'	
  pull_request:
    branches:
      - '*'	

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        entry:
          - { java: "8", distribution: "temurin" }
          - { java: "11", distribution: "temurin" }
          - { java: "11", distribution: "microsoft" }
          - { java: "17", distribution: "temurin" }
          - { java: "17", distribution: "microsoft" }

    runs-on: "windows-2019"

    name: Java ${{ matrix.entry.java }} ( ${{ matrix.entry.distribution }} )
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configuring Developer Command Prompt for Microsoft Visual C++
      - uses: ilammy/msvc-dev-cmd@v1

      # Setup JDK
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.entry.distribution }}
          java-version: ${{ matrix.entry.java }}

      # Default Build
      - run: mvn clean install -B
