name: Log4JNA Deploy

on:
  push:
    branches: [master, dev-ghactions]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: ["8"]
        distribution: ["temurin"]

    runs-on: "windows-2019"

    name: Java ${{ matrix.java }} ( ${{ matrix.distribution }} )
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # configuring Developer Command Prompt for Microsoft Visual C++
      - uses: ilammy/msvc-dev-cmd@v1

      # Setup JDK
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          server-id: osshr
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} 
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      # Deploy
      - run: mvn clean site site:stage deploy -B -P deploy
        env:
          MAVEN_USERNAME: Log4JNACI
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
