name: Log4JNA Site Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        entry:
          - { java: "8", distribution: "temurin" }

    runs-on: "windows-2019"

    name: Java ${{ matrix.entry.java }} ( ${{ matrix.entry.distribution }} )
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configuring Developer Command Prompt for Microsoft Visual C++
      - uses: ilammy/msvc-dev-cmd@v1

      # Setup JDK
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.entry.distribution }}
          java-version: ${{ matrix.entry.java }}

      # Set git config
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true

      # Site Publish
      - run: mvn clean site site:stage scm-publish:publish-scm -P site
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
